name: Tests CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: calculator_test_db
          MYSQL_USER: calculator_test_user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm run test:unit
        
      - name: Setup test database
        run: node src/tests/setup/setupDatabase.js
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          MARIADB_ROOT_USER: root
          MARIADB_ROOT_PASSWORD: root_password
          DB_NAME: calculator_test_db
          DB_USER: calculator_test_user
          DB_PASSWORD: password
        
      - name: Run integration tests
        run: npm run test:integration
        env:
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: calculator_test_db
          DB_USER: calculator_test_user
          DB_PASSWORD: password